name: Swift

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app && /usr/bin/xcodebuild -version
      - name: Run tests
        run: xcodebuild test -scheme JsonDecodeProtection -project JsonDecodeProtection.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' | xcpretty && exit ${PIPESTATUS[0]}
