name: Swift

on:
 push:
   branches:
     - main

jobs:
  build:
    
    runs-on: macos-15.1.1
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.0.app && /usr/bin/xcodebuild -version
      - name: Run tests
        run: xcodebuild test -scheme JsonDecodeProtection -project JsonDecodeProtection.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' | xcpretty && exit ${PIPESTATUS[0]}
