name: Swift

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: macos-15
    
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app && /usr/bin/xcodebuild -version

      - name: Build for iOS
        uses: mxcl/xcodebuild@v3
        with:
          platform: iOS
          xcode: ^16.4
          scheme: JsonDecodeProtection
          action: build

      - name: Runing tests for iOS
        uses: mxcl/xcodebuild@v3
        with:
          platform: iOS
          xcode: ^16.4
          scheme: JsonDecodeProtection
          action: test
 