name: Swift

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: macos-15
    
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app && /usr/bin/xcodebuild -version

      - name: Build for iOS
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: JsonDecodeProtection.xcodeproj
          scheme: JsonDecodeProtection
          destination: platform=iOS Simulator,name=iPhone 16,OS=18.6
          action: build 

      - name: Runing tests for iOS
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: JsonDecodeProtection.xcodeproj
          scheme: JsonDecodeProtection
          destination: platform=iOS Simulator,name=iPhone 16,OS=18.6
          action: test
 