name: Swift

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: macos-15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1.0"

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test
 